# -*- coding: utf-8 -*-
"""run_semgrep_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzONbIJZwRSADrrCCJ0r4Gi434xJiXeS
"""

# run_semgrep_analysis.py
# Static security analysis using Semgrep on the HTTPie repository

import os
import json
import subprocess

# Step 1: Clone the target repository
os.system("git clone https://github.com/httpie/httpie.git")
os.chdir("httpie")

# Step 2: Run Semgrep analysis and export JSON results
subprocess.run([
    "semgrep", "ci",
    "--json",
    "--output", "httpie_report_ci.json"
], check=True)

# Step 3: Parse and display summary results
with open("httpie_report_ci.json") as f:
    data = json.load(f)

print(f"Project: HTTPie | Findings: {len(data.get('results', []))}")
print("=" * 80)

for r in data.get("results", []):
    path = r.get("path")
    msg = r.get("extra", {}).get("message", "")
    severity = r.get("extra", {}).get("severity", "")
    cwe = r.get("extra", {}).get("metadata", {}).get("cwe", [])
    print(f"File: {path}")
    print(f"Issue: {msg}")
    print(f"Severity: {severity}")
    print(f"CWE: {', '.join(cwe) if cwe else 'N/A'}")
    print("-" * 80)